import {
  MAX_DICTIONARY_DESCRIPTION_LENGTH,
  MAX_DICTIONARY_NAME_LENGTH,
  MIN_DICTIONARY_NAME_LENGTH,
} from '../constants/dictionary';
import {
  Router,
  LoginScreen,
  LoginForm,
  RegistrationForm,
  MainScreen,
  CardScreen,
  AssociationModal,
  ImagesModal,
  PersonalDictionariesScreen,
  CreateDictionaryModal,
  ShowAssociationsModal,
} from './keys';

export const ru = {
  [Router.RegistationScreenTitle]: 'Регистрация',
  [Router.LoginScreenTitle]: 'Авторизация',
  [Router.MainScreenTitle]: 'Главное меню',
  [Router.CardScreenTitle]: 'Карточка',
  [Router.DictionariesScreenTitle]: 'Словари',
  [Router.DictionaryScreenTitle]: 'Словарь',
  [Router.PublicDictionariesTitle]: 'Публичные словари',
  [Router.PersonalDictionariesTitle]: 'Персональные словари',

  [LoginForm.UsernameLabel]: 'Псевдоним',
  [LoginForm.UsernamePlaceholder]: 'Введите ваш псевдоним',
  [LoginForm.UsernameErrorRequired]: 'Введите псевдоним',
  [LoginForm.UsernameErrorShort]: 'Псевдоним слишком короткий',
  [LoginForm.UsernameErrorLong]: 'Псевдоним слишком длинный',
  [LoginForm.PasswordLabel]: 'Пароль',
  [LoginForm.PasswordErrorRequired]: 'Введите пароль',
  [LoginForm.PasswordErrorShort]: 'Пароль слишком короткий',
  [LoginForm.AuthButton]: 'Войти',
  [LoginScreen.RegistrationButton]: 'Создать аккаунт',

  [RegistrationForm.UsernameLabel]: 'Псевдоним',
  [RegistrationForm.UsernamePlaceholder]: 'Гарфилд',
  [RegistrationForm.UsernameErrorRequired]: 'Введите псевдоним',
  [RegistrationForm.UsernameErrorShort]: 'Псевдоним слишком короткий',
  [RegistrationForm.UsernameErrorLong]: 'Псевдоним слишком длинный',
  [RegistrationForm.MailLabel]: 'Электронная почта',
  [RegistrationForm.MailPlaceholder]: 'garfield@cat.com',
  [RegistrationForm.MailErrorRequired]: 'Введите электронную почту',
  [RegistrationForm.MailErrorInvalid]: 'Неверная электронная почта',
  [RegistrationForm.PasswordLabel]: 'Пароль',
  [RegistrationForm.RepeatPasswordLabel]: 'Повторите пароль',
  [RegistrationForm.PasswordErrorRequired]: 'Введите пароль',
  [RegistrationForm.PasswordErrorShort]: 'Пароль слишком короткий',
  [RegistrationForm.PasswordErrorMatch]: 'Пароли не совпадают',
  [RegistrationForm.PasswordErrorRepeat]: 'Повторите пароль, пожалуйста',
  [RegistrationForm.RegistrationButton]: 'Создать аккаунт',

  [MainScreen.Header]: 'Доброго времени суток,',
  [MainScreen.AddCardButton]: 'Добавить карточку',
  [MainScreen.LookDictionariesButton]: 'Посмотреть словари',
  [MainScreen.GamesButton]: 'Игры',
  [MainScreen.LogoutButton]: 'Выйти из аккаунта',

  [CardScreen.PhrasePlaceholder]: 'Введите фразу для перевода',
  [CardScreen.PhraseButton]: 'Найти перевод',
  [CardScreen.TranslatePlaceholder]: 'Введите перевод фразы',
  [CardScreen.TranslateButton]: 'Добавить перевод',
  [CardScreen.AssociationButton]: 'Создать ассоциацию',

  [AssociationModal.Header]: 'Список ассоциаций',
  [AssociationModal.DictionaryPlaceholder]: 'Выберите словарь',
  [AssociationModal.CardButton]: 'Создать карточку',

  [ImagesModal.Header]: 'Создание ассоциации',
  [ImagesModal.TranslationsLabel]:
    'Выберите переводы, которые хотите включить в ассоциацию',
  [ImagesModal.AddAboutButton]: 'Добавить описание',
  [ImagesModal.DeleteAboutButton]: 'Удалить описание',
  [ImagesModal.AboutPlaceholder]: 'Введите описание',
  [ImagesModal.ImagePlaceholder]: 'Введите фразу для поиска изображения',
  [ImagesModal.ImageButton]: 'Найти изображение',
  [ImagesModal.AssociationButton]: 'Создать ассоциацию',

  [PersonalDictionariesScreen.CreateDictionaryButton]: 'Создать новый словарь',
  [PersonalDictionariesScreen.DictionariesNotFoundText]: 'Словари не найдены :(',

  [CreateDictionaryModal.Header]: 'Новый словарь',
  [CreateDictionaryModal.NameLabel]: 'Введите название словаря',
  [CreateDictionaryModal.NamePlaceholder]: 'Название словаря',
  [CreateDictionaryModal.NameErrorRequired]: 'Это поле не может быть пустым',
  [CreateDictionaryModal.NameErrorShort]: `Название словаря должно быть больше ${MIN_DICTIONARY_NAME_LENGTH}`,
  [CreateDictionaryModal.NameErrorLong]: `Название словаря должно быть меньше ${MAX_DICTIONARY_NAME_LENGTH}`,
  [CreateDictionaryModal.DescriptionLabel]: 'Введите описание словаря',
  [CreateDictionaryModal.DescriptionPlaceholder]: 'Описание словаря',
  [CreateDictionaryModal.DescriptionErrorRequired]: 'Это поле не может быть пустым',
  [CreateDictionaryModal.DescriptionErrorLong]: `Описание словаря должно быть меньше ${MAX_DICTIONARY_DESCRIPTION_LENGTH}`,
  [CreateDictionaryModal.PrivateCheckboxLabel]: 'Приватный словарь',
  [CreateDictionaryModal.CreateButton]: 'Создать',

  [ShowAssociationsModal.Header]: 'Ассоциации',
};
