import { Router, LoginScreen, LoginForm, RegistrationForm, MainScreen } from './keys';

export const ru = {
  [Router.RegistationScreenTitle]: 'Регистрация',
  [Router.LoginScreenTitle]: 'Авторизация',
  [Router.MainScreenTitle]: 'Главное меню',

  [LoginForm.UsernameLabel]: 'Псевдоним',
  [LoginForm.UsernamePlaceholder]: 'Введите ваш псевдоним',
  [LoginForm.UsernameErrorRequired]: 'Введите псевдоним',
  [LoginForm.UsernameErrorShort]: 'Псевдоним слишком короткий',
  [LoginForm.UsernameErrorLong]: 'Псевдоним слишком длинный',
  [LoginForm.PasswordLabel]: 'Пароль',
  [LoginForm.PasswordErrorRequired]: 'Введите пароль',
  [LoginForm.PasswordErrorShort]: 'Пароль слишком короткий',
  [LoginForm.AuthButton]: 'Войти',
  [LoginScreen.RegistrationButton]: 'Создать аккаунт',

  [RegistrationForm.UsernameLabel]: 'Псевдоним',
  [RegistrationForm.UsernamePlaceholder]: 'Гарфилд',
  [RegistrationForm.UsernameErrorRequired]: 'Введите псевдоним',
  [RegistrationForm.UsernameErrorShort]: 'Псевдоним слишком короткий',
  [RegistrationForm.UsernameErrorLong]: 'Псевдоним слишком длинный',
  [RegistrationForm.MailLabel]: 'Электронная почта',
  [RegistrationForm.MailPlaceholder]: 'garfield@cat.com',
  [RegistrationForm.MailErrorRequired]: 'Введите электронную почту',
  [RegistrationForm.MailErrorInvalid]: 'Неверная электронная почта',
  [RegistrationForm.PasswordLabel]: 'Пароль',
  [RegistrationForm.RepeatPasswordLabel]: 'Повторите пароль',
  [RegistrationForm.PasswordErrorRequired]: 'Введите пароль',
  [RegistrationForm.PasswordErrorShort]: 'Пароль слишком короткий',
  [RegistrationForm.PasswordErrorMatch]: 'Пароли не совпадают',
  [RegistrationForm.PasswordErrorRepeat]: 'Повторите пароль, пожалуйста',
  [RegistrationForm.RegistrationButton]: 'Создать аккаунт',

  [MainScreen.Header]: 'Доброго времени суток,',
  [MainScreen.AddCardButton]: 'Добавить карточку',
  [MainScreen.LookDictionariesButton]: 'Посмотреть словари',
  [MainScreen.GamesButton]: 'Игры',
  [MainScreen.LogoutButton]: 'Выйти из аккаунта',
};
